/* =============================================================================
 *   Copyright (c) Texas Instruments Incorporated 2018
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
 
#ifndef PMTEST_TESTSLIST_AM65XX_H_
#define PMTEST_TESTSLIST_AM65XX_H_

/* ========================================================================== */
/*                                Include Files                               */
/* ========================================================================== */

#include <stdint.h>
#include <ti/drv/sciclient/sciclient.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */

/* None */

/* ========================================================================== */
/*                         Structures and Enums                               */
/* ========================================================================== */

/**
 * \brief Structure to define an input clock to a module.
 */
typedef struct
{
    uint32_t modId;
    /**< module Id */
    uint32_t clkId;
    /**< clock Id */
    uint64_t clkRate;
    /**< Supported clock rate */
} Pmtest_inputClk_t;

/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/* Used to test all possible frequencies for all clocks and modules.*/
Pmtest_inputClk_t gPmtest_setFreqTestList[] =
{
    {
        TISCI_DEV_BOARD0,
        TISCI_DEV_BOARD0_BUS_MCU_OBSCLK_IN_PARENT_MX_WAKEUP_GS80_WKUP_0_BUS_WKUP_RCOSC_32K_CLK,
        32000
    },
    {
        TISCI_DEV_BOARD0,
        TISCI_DEV_BOARD0_BUS_OBSCLK_IN_PARENT_GLUELOGIC_LFOSC_CLK_BUS_OUT,
        32768
    },
    {
        TISCI_DEV_BOARD0,
        TISCI_DEV_BOARD0_BUS_MCU_OBSCLK_IN_PARENT_GLUELOGIC_LFOSC_CLK_BUS_OUT,
        32768
    },
    {
        TISCI_DEV_MCU_ADC0,
        TISCI_DEV_MCU_ADC0_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_MCU_ADC0,
        TISCI_DEV_MCU_ADC0_BUS_SYS_CLK,
        0
    },
    {
        TISCI_DEV_MCU_ADC0,
        TISCI_DEV_MCU_ADC0_BUS_ADC_CLK,
        25000000
    },
    {
        TISCI_DEV_MCU_ADC0,
        TISCI_DEV_MCU_ADC0_BUS_ADC_CLK,
        60000000
    },
    {
        TISCI_DEV_MCU_ADC1,
        TISCI_DEV_MCU_ADC1_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_MCU_ADC1,
        TISCI_DEV_MCU_ADC1_BUS_SYS_CLK,
        0
    },
    {
        TISCI_DEV_MCU_ADC1,
        TISCI_DEV_MCU_ADC1_BUS_ADC_CLK,
        25000000
    },
    {
        TISCI_DEV_MCU_ADC1,
        TISCI_DEV_MCU_ADC1_BUS_ADC_CLK,
        60000000
    },
    {
        TISCI_DEV_CAL0,
        TISCI_DEV_CAL0_BUS_CLK,
        0
    },
    {
        TISCI_DEV_CAL0,
        TISCI_DEV_CAL0_BUS_CP_C_CLK,
        0
    },
    {
        TISCI_DEV_CMPEVENT_INTRTR0,
        TISCI_DEV_CMPEVENT_INTRTR0_BUS_INTR_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CPSW0,
        TISCI_DEV_MCU_CPSW0_BUS_GMII1_MR_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CPSW0,
        TISCI_DEV_MCU_CPSW0_BUS_RGMII_MHZ_250_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CPSW0,
        TISCI_DEV_MCU_CPSW0_BUS_CPTS_RFT_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CPSW0,
        TISCI_DEV_MCU_CPSW0_BUS_GMII1_MT_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CPSW0,
        TISCI_DEV_MCU_CPSW0_BUS_RGMII_MHZ_5_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CPSW0,
        TISCI_DEV_MCU_CPSW0_BUS_RMII_MHZ_50_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CPSW0,
        TISCI_DEV_MCU_CPSW0_BUS_RGMII_MHZ_50_CLK,
        0
    },
    /* TODO: This is failing */
    {
        TISCI_DEV_MCU_CPSW0,
        TISCI_DEV_MCU_CPSW0_BUS_RGMII_MHZ_50_CLK,
        50000000
    },
    {
        TISCI_DEV_MCU_CPSW0,
        TISCI_DEV_MCU_CPSW0_BUS_GMII_RFT_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CPSW0,
        TISCI_DEV_MCU_CPSW0_BUS_CPPI_CLK_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CPSW0,
        TISCI_DEV_MCU_CPSW0_BUS_CPTS_GENF0_0,
        0
    },
    {
        TISCI_DEV_CPT2_AGGR0,
        TISCI_DEV_CPT2_AGGR0_BUS_VCLK_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CPT2_AGGR0,
        TISCI_DEV_MCU_CPT2_AGGR0_BUS_VCLK_CLK,
        0
    },
    {
        TISCI_DEV_STM0,
        TISCI_DEV_STM0_BUS_CORE_CLK,
        0
    },
    {
        TISCI_DEV_STM0,
        TISCI_DEV_STM0_BUS_ATB_CLK,
        0
    },
    {
        TISCI_DEV_STM0,
        TISCI_DEV_STM0_BUS_VBUSP_CLK,
        0
    },
    /* TODO */
    {
        TISCI_DEV_DCC0,
        TISCI_DEV_DCC0_BUS_DCC_INPUT00_CLK,
        0
    },
    {
        TISCI_DEV_DCC0,
        TISCI_DEV_DCC0_BUS_DCC_CLKSRC4_CLK,
        0
    },
    {
        TISCI_DEV_DCC0,
        TISCI_DEV_DCC0_BUS_DCC_CLKSRC3_CLK,
        0
    },
    {
        TISCI_DEV_DCC0,
        TISCI_DEV_DCC0_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_DCC0,
        TISCI_DEV_DCC0_BUS_DCC_CLKSRC1_CLK,
        0
    },
    {
        TISCI_DEV_DCC0,
        TISCI_DEV_DCC0_BUS_DCC_INPUT01_CLK,
        0
    },
    {
        TISCI_DEV_DCC0,
        TISCI_DEV_DCC0_BUS_DCC_CLKSRC5_CLK,
        0
    },
    {
        TISCI_DEV_DCC0,
        TISCI_DEV_DCC0_BUS_DCC_INPUT02_CLK,
        0
    },
    {
        TISCI_DEV_DCC0,
        TISCI_DEV_DCC0_BUS_DCC_CLKSRC0_CLK,
        0
    },
    {
        TISCI_DEV_DCC0,
        TISCI_DEV_DCC0_BUS_DCC_CLKSRC6_CLK,
        0
    },
    {
        TISCI_DEV_DCC0,
        TISCI_DEV_DCC0_BUS_DCC_INPUT10_CLK,
        0
    },
    {
        TISCI_DEV_DCC0,
        TISCI_DEV_DCC0_BUS_DCC_CLKSRC2_CLK,
        0
    },
    {
        TISCI_DEV_DCC1,
        TISCI_DEV_DCC1_BUS_DCC_INPUT00_CLK,
        0
    },
    {
        TISCI_DEV_DCC1,
        TISCI_DEV_DCC1_BUS_DCC_CLKSRC7_CLK,
        0
    },
    {
        TISCI_DEV_DCC1,
        TISCI_DEV_DCC1_BUS_DCC_CLKSRC4_CLK,
        0
    },
    {
        TISCI_DEV_DCC1,
        TISCI_DEV_DCC1_BUS_DCC_CLKSRC3_CLK,
        0
    },
    {
        TISCI_DEV_DCC1,
        TISCI_DEV_DCC1_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_DCC1,
        TISCI_DEV_DCC1_BUS_DCC_CLKSRC1_CLK,
        0
    },
    {
        TISCI_DEV_DCC1,
        TISCI_DEV_DCC1_BUS_DCC_INPUT01_CLK,
        0
    },
    {
        TISCI_DEV_DCC1,
        TISCI_DEV_DCC1_BUS_DCC_CLKSRC5_CLK,
        0
    },
    {
        TISCI_DEV_DCC1,
        TISCI_DEV_DCC1_BUS_DCC_INPUT02_CLK,
        0
    },
    {
        TISCI_DEV_DCC1,
        TISCI_DEV_DCC1_BUS_DCC_CLKSRC0_CLK,
        0
    },
    {
        TISCI_DEV_DCC1,
        TISCI_DEV_DCC1_BUS_DCC_CLKSRC6_CLK,
        0
    },
    {
        TISCI_DEV_DCC1,
        TISCI_DEV_DCC1_BUS_DCC_INPUT10_CLK,
        0
    },
    {
        TISCI_DEV_DCC1,
        TISCI_DEV_DCC1_BUS_DCC_CLKSRC2_CLK,
        0
    },
    {
        TISCI_DEV_DCC2,
        TISCI_DEV_DCC2_BUS_DCC_INPUT00_CLK,
        0
    },
    {
        TISCI_DEV_DCC2,
        TISCI_DEV_DCC2_BUS_DCC_CLKSRC7_CLK,
        0
    },
    {
        TISCI_DEV_DCC2,
        TISCI_DEV_DCC2_BUS_DCC_CLKSRC4_CLK,
        0
    },
    {
        TISCI_DEV_DCC2,
        TISCI_DEV_DCC2_BUS_DCC_CLKSRC3_CLK,
        0
    },
    {
        TISCI_DEV_DCC2,
        TISCI_DEV_DCC2_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_DCC2,
        TISCI_DEV_DCC2_BUS_DCC_CLKSRC1_CLK,
        0
    },
    {
        TISCI_DEV_DCC2,
        TISCI_DEV_DCC2_BUS_DCC_INPUT01_CLK,
        0
    },
    {
        TISCI_DEV_DCC2,
        TISCI_DEV_DCC2_BUS_DCC_CLKSRC5_CLK,
        0
    },
    {
        TISCI_DEV_DCC2,
        TISCI_DEV_DCC2_BUS_DCC_INPUT02_CLK,
        0
    },
    {
        TISCI_DEV_DCC2,
        TISCI_DEV_DCC2_BUS_DCC_CLKSRC0_CLK,
        0
    },
    {
        TISCI_DEV_DCC2,
        TISCI_DEV_DCC2_BUS_DCC_CLKSRC6_CLK,
        0
    },
    {
        TISCI_DEV_DCC2,
        TISCI_DEV_DCC2_BUS_DCC_INPUT10_CLK,
        0
    },
    {
        TISCI_DEV_DCC2,
        TISCI_DEV_DCC2_BUS_DCC_CLKSRC2_CLK,
        0
    },
    {
        TISCI_DEV_DCC3,
        TISCI_DEV_DCC3_BUS_DCC_INPUT00_CLK,
        0
    },
    {
        TISCI_DEV_DCC3,
        TISCI_DEV_DCC3_BUS_DCC_CLKSRC7_CLK,
        0
    },
    {
        TISCI_DEV_DCC3,
        TISCI_DEV_DCC3_BUS_DCC_CLKSRC4_CLK,
        0
    },
    {
        TISCI_DEV_DCC3,
        TISCI_DEV_DCC3_BUS_DCC_CLKSRC3_CLK,
        0
    },
    {
        TISCI_DEV_DCC3,
        TISCI_DEV_DCC3_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_DCC3,
        TISCI_DEV_DCC3_BUS_DCC_CLKSRC1_CLK,
        0
    },
    {
        TISCI_DEV_DCC3,
        TISCI_DEV_DCC3_BUS_DCC_INPUT01_CLK,
        0
    },
    {
        TISCI_DEV_DCC3,
        TISCI_DEV_DCC3_BUS_DCC_CLKSRC5_CLK,
        0
    },
    {
        TISCI_DEV_DCC3,
        TISCI_DEV_DCC3_BUS_DCC_INPUT02_CLK,
        0
    },
    {
        TISCI_DEV_DCC3,
        TISCI_DEV_DCC3_BUS_DCC_CLKSRC0_CLK,
        0
    },
    {
        TISCI_DEV_DCC3,
        TISCI_DEV_DCC3_BUS_DCC_INPUT10_CLK,
        0
    },
    {
        TISCI_DEV_DCC3,
        TISCI_DEV_DCC3_BUS_DCC_CLKSRC2_CLK,
        0
    },
    {
        TISCI_DEV_DCC4,
        TISCI_DEV_DCC4_BUS_DCC_INPUT00_CLK,
        0
    },
    {
        TISCI_DEV_DCC4,
        TISCI_DEV_DCC4_BUS_DCC_CLKSRC7_CLK,
        0
    },
    {
        TISCI_DEV_DCC4,
        TISCI_DEV_DCC4_BUS_DCC_CLKSRC4_CLK,
        0
    },
    {
        TISCI_DEV_DCC4,
        TISCI_DEV_DCC4_BUS_DCC_CLKSRC3_CLK,
        0
    },
    {
        TISCI_DEV_DCC4,
        TISCI_DEV_DCC4_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_DCC4,
        TISCI_DEV_DCC4_BUS_DCC_INPUT01_CLK,
        0
    },
    {
        TISCI_DEV_DCC4,
        TISCI_DEV_DCC4_BUS_DCC_CLKSRC5_CLK,
        0
    },
    {
        TISCI_DEV_DCC4,
        TISCI_DEV_DCC4_BUS_DCC_INPUT02_CLK,
        0
    },
    {
        TISCI_DEV_DCC4,
        TISCI_DEV_DCC4_BUS_DCC_CLKSRC0_CLK,
        0
    },
    {
        TISCI_DEV_DCC4,
        TISCI_DEV_DCC4_BUS_DCC_CLKSRC6_CLK,
        0
    },
    {
        TISCI_DEV_DCC4,
        TISCI_DEV_DCC4_BUS_DCC_INPUT10_CLK,
        0
    },
    {
        TISCI_DEV_DCC4,
        TISCI_DEV_DCC4_BUS_DCC_CLKSRC2_CLK,
        0
    },
    {
        TISCI_DEV_DCC5,
        TISCI_DEV_DCC5_BUS_DCC_INPUT00_CLK,
        0
    },
    {
        TISCI_DEV_DCC5,
        TISCI_DEV_DCC5_BUS_DCC_CLKSRC7_CLK,
        0
    },
    {
        TISCI_DEV_DCC5,
        TISCI_DEV_DCC5_BUS_DCC_CLKSRC4_CLK,
        0
    },
    {
        TISCI_DEV_DCC5,
        TISCI_DEV_DCC5_BUS_DCC_CLKSRC3_CLK,
        0
    },
    {
        TISCI_DEV_DCC5,
        TISCI_DEV_DCC5_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_DCC5,
        TISCI_DEV_DCC5_BUS_DCC_CLKSRC1_CLK,
        0
    },
    {
        TISCI_DEV_DCC5,
        TISCI_DEV_DCC5_BUS_DCC_INPUT01_CLK,
        0
    },
    {
        TISCI_DEV_DCC5,
        TISCI_DEV_DCC5_BUS_DCC_CLKSRC5_CLK,
        0
    },
    {
        TISCI_DEV_DCC5,
        TISCI_DEV_DCC5_BUS_DCC_INPUT02_CLK,
        0
    },
    {
        TISCI_DEV_DCC5,
        TISCI_DEV_DCC5_BUS_DCC_CLKSRC0_CLK,
        0
    },
    {
        TISCI_DEV_DCC5,
        TISCI_DEV_DCC5_BUS_DCC_CLKSRC6_CLK,
        0
    },
    {
        TISCI_DEV_DCC5,
        TISCI_DEV_DCC5_BUS_DCC_INPUT10_CLK,
        0
    },
    {
        TISCI_DEV_DCC5,
        TISCI_DEV_DCC5_BUS_DCC_CLKSRC2_CLK,
        0
    },
    {
        TISCI_DEV_DCC6,
        TISCI_DEV_DCC6_BUS_DCC_INPUT00_CLK,
        0
    },
    {
        TISCI_DEV_DCC6,
        TISCI_DEV_DCC6_BUS_DCC_CLKSRC7_CLK,
        0
    },
    {
        TISCI_DEV_DCC6,
        TISCI_DEV_DCC6_BUS_DCC_CLKSRC4_CLK,
        0
    },
    {
        TISCI_DEV_DCC6,
        TISCI_DEV_DCC6_BUS_DCC_CLKSRC3_CLK,
        0
    },
    {
        TISCI_DEV_DCC6,
        TISCI_DEV_DCC6_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_DCC6,
        TISCI_DEV_DCC6_BUS_DCC_CLKSRC1_CLK,
        0
    },
    {
        TISCI_DEV_DCC6,
        TISCI_DEV_DCC6_BUS_DCC_INPUT01_CLK,
        0
    },
    {
        TISCI_DEV_DCC6,
        TISCI_DEV_DCC6_BUS_DCC_CLKSRC5_CLK,
        0
    },
    {
        TISCI_DEV_DCC6,
        TISCI_DEV_DCC6_BUS_DCC_INPUT02_CLK,
        0
    },
    {
        TISCI_DEV_DCC6,
        TISCI_DEV_DCC6_BUS_DCC_CLKSRC0_CLK,
        0
    },
    {
        TISCI_DEV_DCC6,
        TISCI_DEV_DCC6_BUS_DCC_CLKSRC6_CLK,
        0
    },
    {
        TISCI_DEV_DCC6,
        TISCI_DEV_DCC6_BUS_DCC_INPUT10_CLK,
        0
    },
    {
        TISCI_DEV_DCC6,
        TISCI_DEV_DCC6_BUS_DCC_CLKSRC2_CLK,
        0
    },
    {
        TISCI_DEV_DCC7,
        TISCI_DEV_DCC7_BUS_DCC_INPUT00_CLK,
        0
    },
    {
        TISCI_DEV_DCC7,
        TISCI_DEV_DCC7_BUS_DCC_CLKSRC7_CLK,
        0
    },
    {
        TISCI_DEV_DCC7,
        TISCI_DEV_DCC7_BUS_DCC_CLKSRC4_CLK,
        0
    },
    {
        TISCI_DEV_DCC7,
        TISCI_DEV_DCC7_BUS_DCC_CLKSRC3_CLK,
        0
    },
    {
        TISCI_DEV_DCC7,
        TISCI_DEV_DCC7_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_DCC7,
        TISCI_DEV_DCC7_BUS_DCC_CLKSRC1_CLK,
        0
    },
    {
        TISCI_DEV_DCC7,
        TISCI_DEV_DCC7_BUS_DCC_INPUT01_CLK,
        0
    },
    {
        TISCI_DEV_DCC7,
        TISCI_DEV_DCC7_BUS_DCC_CLKSRC5_CLK,
        0
    },
    {
        TISCI_DEV_DCC7,
        TISCI_DEV_DCC7_BUS_DCC_INPUT02_CLK,
        0
    },
    {
        TISCI_DEV_DCC7,
        TISCI_DEV_DCC7_BUS_DCC_CLKSRC0_CLK,
        0
    },
    {
        TISCI_DEV_DCC7,
        TISCI_DEV_DCC7_BUS_DCC_CLKSRC6_CLK,
        0
    },
    {
        TISCI_DEV_DCC7,
        TISCI_DEV_DCC7_BUS_DCC_INPUT10_CLK,
        0
    },
    {
        TISCI_DEV_DCC7,
        TISCI_DEV_DCC7_BUS_DCC_CLKSRC2_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC0,
        TISCI_DEV_MCU_DCC0_BUS_DCC_INPUT00_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC0,
        TISCI_DEV_MCU_DCC0_BUS_DCC_CLKSRC7_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC0,
        TISCI_DEV_MCU_DCC0_BUS_DCC_CLKSRC4_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC0,
        TISCI_DEV_MCU_DCC0_BUS_DCC_CLKSRC3_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC0,
        TISCI_DEV_MCU_DCC0_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC0,
        TISCI_DEV_MCU_DCC0_BUS_DCC_CLKSRC1_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC0,
        TISCI_DEV_MCU_DCC0_BUS_DCC_INPUT01_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC0,
        TISCI_DEV_MCU_DCC0_BUS_DCC_CLKSRC5_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC0,
        TISCI_DEV_MCU_DCC0_BUS_DCC_INPUT02_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC0,
        TISCI_DEV_MCU_DCC0_BUS_DCC_CLKSRC0_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC0,
        TISCI_DEV_MCU_DCC0_BUS_DCC_CLKSRC6_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC0,
        TISCI_DEV_MCU_DCC0_BUS_DCC_INPUT10_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC0,
        TISCI_DEV_MCU_DCC0_BUS_DCC_CLKSRC2_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC1,
        TISCI_DEV_MCU_DCC1_BUS_DCC_INPUT00_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC1,
        TISCI_DEV_MCU_DCC1_BUS_DCC_CLKSRC7_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC1,
        TISCI_DEV_MCU_DCC1_BUS_DCC_CLKSRC4_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC1,
        TISCI_DEV_MCU_DCC1_BUS_DCC_CLKSRC3_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC1,
        TISCI_DEV_MCU_DCC1_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC1,
        TISCI_DEV_MCU_DCC1_BUS_DCC_CLKSRC1_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC1,
        TISCI_DEV_MCU_DCC1_BUS_DCC_INPUT01_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC1,
        TISCI_DEV_MCU_DCC1_BUS_DCC_CLKSRC5_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC1,
        TISCI_DEV_MCU_DCC1_BUS_DCC_INPUT02_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC1,
        TISCI_DEV_MCU_DCC1_BUS_DCC_CLKSRC0_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC1,
        TISCI_DEV_MCU_DCC1_BUS_DCC_CLKSRC6_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC1,
        TISCI_DEV_MCU_DCC1_BUS_DCC_INPUT10_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC1,
        TISCI_DEV_MCU_DCC1_BUS_DCC_CLKSRC2_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC2,
        TISCI_DEV_MCU_DCC2_BUS_DCC_INPUT00_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC2,
        TISCI_DEV_MCU_DCC2_BUS_DCC_CLKSRC7_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC2,
        TISCI_DEV_MCU_DCC2_BUS_DCC_CLKSRC4_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC2,
        TISCI_DEV_MCU_DCC2_BUS_DCC_CLKSRC3_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC2,
        TISCI_DEV_MCU_DCC2_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC2,
        TISCI_DEV_MCU_DCC2_BUS_DCC_CLKSRC1_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC2,
        TISCI_DEV_MCU_DCC2_BUS_DCC_INPUT01_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC2,
        TISCI_DEV_MCU_DCC2_BUS_DCC_CLKSRC5_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC2,
        TISCI_DEV_MCU_DCC2_BUS_DCC_INPUT02_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC2,
        TISCI_DEV_MCU_DCC2_BUS_DCC_CLKSRC0_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC2,
        TISCI_DEV_MCU_DCC2_BUS_DCC_CLKSRC6_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC2,
        TISCI_DEV_MCU_DCC2_BUS_DCC_INPUT10_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DCC2,
        TISCI_DEV_MCU_DCC2_BUS_DCC_CLKSRC2_CLK,
        0
    },
    /* TODO */
    {
        TISCI_DEV_DDRSS0,
        TISCI_DEV_DDRSS0_BUS_DDRSS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_DDRSS0,
        TISCI_DEV_DDRSS0_BUS_DDRSS_BYP_4X_CLK,
        0
    },
    {
        TISCI_DEV_DDRSS0,
        TISCI_DEV_DDRSS0_BUS_DDRSS_CTL_CLK_BUS_IN1_ADPLLLJM_WRAP_MAIN_3_BUS_CLKOUT_CLK,
        0
    },
    {
        TISCI_DEV_DDRSS0,
        TISCI_DEV_DDRSS0_BUS_DDRSS_TCLK,
        0
    },
    {
        TISCI_DEV_DDRSS0,
        TISCI_DEV_DDRSS0_BUS_DDRSS_PHY_CTL_CLK_BUS_IN1_ADPLLLJM_WRAP_MAIN_3_BUS_CLKOUT_CLK,
        0
    },
    {
        TISCI_DEV_DDRSS0,
        TISCI_DEV_DDRSS0_BUS_DDRSS_PHY_CTL_CLK_BUS_IN0_ADPLLLJM_WRAP_MAIN_3_BUS_CLKOUT_CLK,
        0
    },
    {
        TISCI_DEV_DDRSS0,
        TISCI_DEV_DDRSS0_BUS_DDRSS_CFG_CLK,
        0
    },
    {
        TISCI_DEV_DDRSS0,
        TISCI_DEV_DDRSS0_BUS_DDRSS_CTL_CLK_BUS_IN0_ADPLLLJM_WRAP_MAIN_3_BUS_CLKOUT_CLK,
        0
    },
    {
        TISCI_DEV_DDRSS0,
        TISCI_DEV_DDRSS0_BUS_DDRSS_BYP_CLK_BUS_IN1_ADPLLLJM_WRAP_MAIN_3_BUS_CLKOUT_CLK,
        0
    },
    {
        TISCI_DEV_DDRSS0,
        TISCI_DEV_DDRSS0_BUS_DDRSS_BYP_CLK_BUS_IN0_ADPLLLJM_WRAP_MAIN_3_BUS_CLKOUT_CLK,
        0
    },
    {
        TISCI_DEV_DEBUGSS_WRAP0,
        TISCI_DEV_DEBUGSS_WRAP0_BUS_JTAG_TCK,
        0
    },
    {
        TISCI_DEV_DEBUGSS_WRAP0,
        TISCI_DEV_DEBUGSS_WRAP0_BUS_ATB_CLK,
        0
    },
    {
        TISCI_DEV_DEBUGSS_WRAP0,
        TISCI_DEV_DEBUGSS_WRAP0_BUS_TREXPT_CLK,
        0
    },
    /* Testing Prog. DIV for trace_clk */
    {
        TISCI_DEV_DEBUGSS_WRAP0,
        TISCI_DEV_DEBUGSS_WRAP0_BUS_TREXPT_CLK,
        0
    },
    {
        TISCI_DEV_DEBUGSS_WRAP0,
        TISCI_DEV_DEBUGSS_WRAP0_BUS_TREXPT_CLK,
        960000000
    },
    {
        TISCI_DEV_DEBUGSS_WRAP0,
        TISCI_DEV_DEBUGSS_WRAP0_BUS_TREXPT_CLK,
        192000000
    },
    {
        TISCI_DEV_DEBUGSS_WRAP0,
        TISCI_DEV_DEBUGSS_WRAP0_BUS_TREXPT_CLK,
        160000000
    },
    {
        TISCI_DEV_DEBUGSS_WRAP0,
        TISCI_DEV_DEBUGSS_WRAP0_BUS_TREXPT_CLK,
        30000000
    },
    {
        TISCI_DEV_DEBUGSS_WRAP0,
        TISCI_DEV_DEBUGSS_WRAP0_BUS_CORE_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_DMSC0,
        TISCI_DEV_WKUP_DMSC0_BUS_FUNC_32K_RT_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_DMSC0,
        TISCI_DEV_WKUP_DMSC0_BUS_FUNC_MOSC_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_DMSC0,
        TISCI_DEV_WKUP_DMSC0_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_DMSC0,
        TISCI_DEV_WKUP_DMSC0_BUS_FUNC_32K_RC_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_DMSC0,
        TISCI_DEV_WKUP_DMSC0_BUS_SEC_EFC_FCLK,
        0
    },
    {
        TISCI_DEV_WKUP_DMSC0,
        TISCI_DEV_WKUP_DMSC0_BUS_DAP_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_DMSC0,
        TISCI_DEV_WKUP_DMSC0_BUS_EXT_CLK,
        0
    },
    {
        TISCI_DEV_TIMER0,
        TISCI_DEV_TIMER0_BUS_TIMER_TCLK_CLK,
        250000000
    },
    {
        TISCI_DEV_TIMER0,
        TISCI_DEV_TIMER0_BUS_TIMER_TCLK_CLK,
        12500000
    },
    {
        TISCI_DEV_TIMER0,
        TISCI_DEV_TIMER0_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_TIMER0,
        TISCI_DEV_TIMER0_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER0,
        TISCI_DEV_TIMER0_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER0,
        TISCI_DEV_TIMER0_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_TIMER1,
        TISCI_DEV_TIMER1_BUS_TIMER_TCLK_CLK,
        250000000
    },
    {
        TISCI_DEV_TIMER1,
        TISCI_DEV_TIMER1_BUS_TIMER_TCLK_CLK,
        12500000
    },
    {
        TISCI_DEV_TIMER1,
        TISCI_DEV_TIMER1_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_TIMER1,
        TISCI_DEV_TIMER1_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER1,
        TISCI_DEV_TIMER1_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER1,
        TISCI_DEV_TIMER1_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_TIMER10,
        TISCI_DEV_TIMER10_BUS_TIMER_TCLK_CLK,
        250000000
    },
    {
        TISCI_DEV_TIMER10,
        TISCI_DEV_TIMER10_BUS_TIMER_TCLK_CLK,
        12500000
    },
    {
        TISCI_DEV_TIMER10,
        TISCI_DEV_TIMER10_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_TIMER10,
        TISCI_DEV_TIMER10_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER10,
        TISCI_DEV_TIMER10_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER10,
        TISCI_DEV_TIMER10_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_TIMER11,
        TISCI_DEV_TIMER11_BUS_TIMER_TCLK_CLK,
        250000000
    },
    {
        TISCI_DEV_TIMER11,
        TISCI_DEV_TIMER11_BUS_TIMER_TCLK_CLK,
        12500000
    },
    {
        TISCI_DEV_TIMER11,
        TISCI_DEV_TIMER11_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_TIMER11,
        TISCI_DEV_TIMER11_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER11,
        TISCI_DEV_TIMER11_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER11,
        TISCI_DEV_TIMER11_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_TIMER2,
        TISCI_DEV_TIMER2_BUS_TIMER_TCLK_CLK,
        250000000
    },
    {
        TISCI_DEV_TIMER2,
        TISCI_DEV_TIMER2_BUS_TIMER_TCLK_CLK,
        12500000
    },
    {
        TISCI_DEV_TIMER2,
        TISCI_DEV_TIMER2_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_TIMER2,
        TISCI_DEV_TIMER2_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER2,
        TISCI_DEV_TIMER2_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER2,
        TISCI_DEV_TIMER2_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_TIMER3,
        TISCI_DEV_TIMER3_BUS_TIMER_TCLK_CLK,
        250000000
    },
    {
        TISCI_DEV_TIMER3,
        TISCI_DEV_TIMER3_BUS_TIMER_TCLK_CLK,
        12500000
    },
    {
        TISCI_DEV_TIMER3,
        TISCI_DEV_TIMER3_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_TIMER3,
        TISCI_DEV_TIMER3_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER3,
        TISCI_DEV_TIMER3_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER3,
        TISCI_DEV_TIMER3_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_TIMER4,
        TISCI_DEV_TIMER4_BUS_TIMER_TCLK_CLK,
        250000000
    },
    {
        TISCI_DEV_TIMER4,
        TISCI_DEV_TIMER4_BUS_TIMER_TCLK_CLK,
        12500000
    },
    {
        TISCI_DEV_TIMER4,
        TISCI_DEV_TIMER4_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_TIMER4,
        TISCI_DEV_TIMER4_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER4,
        TISCI_DEV_TIMER4_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER4,
        TISCI_DEV_TIMER4_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_TIMER5,
        TISCI_DEV_TIMER5_BUS_TIMER_TCLK_CLK,
        250000000
    },
    {
        TISCI_DEV_TIMER5,
        TISCI_DEV_TIMER5_BUS_TIMER_TCLK_CLK,
        12500000
    },
    {
        TISCI_DEV_TIMER5,
        TISCI_DEV_TIMER5_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_TIMER5,
        TISCI_DEV_TIMER5_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER5,
        TISCI_DEV_TIMER5_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER5,
        TISCI_DEV_TIMER5_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_TIMER6,
        TISCI_DEV_TIMER6_BUS_TIMER_TCLK_CLK,
        250000000
    },
    {
        TISCI_DEV_TIMER6,
        TISCI_DEV_TIMER6_BUS_TIMER_TCLK_CLK,
        12500000
    },
    {
        TISCI_DEV_TIMER6,
        TISCI_DEV_TIMER6_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_TIMER6,
        TISCI_DEV_TIMER6_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER6,
        TISCI_DEV_TIMER6_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER6,
        TISCI_DEV_TIMER6_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_TIMER7,
        TISCI_DEV_TIMER7_BUS_TIMER_TCLK_CLK,
        250000000
    },
    {
        TISCI_DEV_TIMER7,
        TISCI_DEV_TIMER7_BUS_TIMER_TCLK_CLK,
        12500000
    },
    {
        TISCI_DEV_TIMER7,
        TISCI_DEV_TIMER7_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_TIMER7,
        TISCI_DEV_TIMER7_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER7,
        TISCI_DEV_TIMER7_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER7,
        TISCI_DEV_TIMER7_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_TIMER8,
        TISCI_DEV_TIMER8_BUS_TIMER_TCLK_CLK,
        250000000
    },
    {
        TISCI_DEV_TIMER8,
        TISCI_DEV_TIMER8_BUS_TIMER_TCLK_CLK,
        12500000
    },
    {
        TISCI_DEV_TIMER8,
        TISCI_DEV_TIMER8_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_TIMER8,
        TISCI_DEV_TIMER8_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER8,
        TISCI_DEV_TIMER8_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER8,
        TISCI_DEV_TIMER8_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_TIMER9,
        TISCI_DEV_TIMER9_BUS_TIMER_TCLK_CLK,
        250000000
    },
    {
        TISCI_DEV_TIMER9,
        TISCI_DEV_TIMER9_BUS_TIMER_TCLK_CLK,
        12500000
    },
    {
        TISCI_DEV_TIMER9,
        TISCI_DEV_TIMER9_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_TIMER9,
        TISCI_DEV_TIMER9_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER9,
        TISCI_DEV_TIMER9_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_TIMER9,
        TISCI_DEV_TIMER9_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_MCU_TIMER0,
        TISCI_DEV_MCU_TIMER0_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_MCU_TIMER0,
        TISCI_DEV_MCU_TIMER0_BUS_TIMER_TCLK_CLK,
        25000000
    },
    {
        TISCI_DEV_MCU_TIMER0,
        TISCI_DEV_MCU_TIMER0_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_MCU_TIMER0,
        TISCI_DEV_MCU_TIMER0_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_MCU_TIMER0,
        TISCI_DEV_MCU_TIMER0_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_MCU_TIMER1,
        TISCI_DEV_MCU_TIMER1_BUS_TIMER_TCLK_CLK,
        25000000
    },
    {
        TISCI_DEV_MCU_TIMER1,
        TISCI_DEV_MCU_TIMER1_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_MCU_TIMER1,
        TISCI_DEV_MCU_TIMER1_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_MCU_TIMER1,
        TISCI_DEV_MCU_TIMER1_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_MCU_TIMER1,
        TISCI_DEV_MCU_TIMER1_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_MCU_TIMER2,
        TISCI_DEV_MCU_TIMER2_BUS_TIMER_TCLK_CLK,
        25000000
    },
    {
        TISCI_DEV_MCU_TIMER2,
        TISCI_DEV_MCU_TIMER2_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_MCU_TIMER2,
        TISCI_DEV_MCU_TIMER2_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_MCU_TIMER2,
        TISCI_DEV_MCU_TIMER2_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_MCU_TIMER2,
        TISCI_DEV_MCU_TIMER2_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_MCU_TIMER3,
        TISCI_DEV_MCU_TIMER3_BUS_TIMER_TCLK_CLK,
        25000000
    },
    {
        TISCI_DEV_MCU_TIMER3,
        TISCI_DEV_MCU_TIMER3_BUS_TIMER_TCLK_CLK,
        200000000
    },
    {
        TISCI_DEV_MCU_TIMER3,
        TISCI_DEV_MCU_TIMER3_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_MCU_TIMER3,
        TISCI_DEV_MCU_TIMER3_BUS_TIMER_TCLK_CLK,
        32000
    },
    {
        TISCI_DEV_MCU_TIMER3,
        TISCI_DEV_MCU_TIMER3_BUS_TIMER_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_ECAP0,
        TISCI_DEV_ECAP0_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_EHRPWM0,
        TISCI_DEV_EHRPWM0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_EHRPWM1,
        TISCI_DEV_EHRPWM1_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_EHRPWM2,
        TISCI_DEV_EHRPWM2_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_EHRPWM3,
        TISCI_DEV_EHRPWM3_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_EHRPWM4,
        TISCI_DEV_EHRPWM4_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_EHRPWM5,
        TISCI_DEV_EHRPWM5_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_ELM0,
        TISCI_DEV_ELM0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MMCSD0,
        TISCI_DEV_MMCSD0_BUS_EMMCSDSS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_MMCSD0,
        TISCI_DEV_MMCSD0_BUS_EMMCSDSS_XIN_CLK,
        0
    },
    {
        TISCI_DEV_MMCSD1,
        TISCI_DEV_MMCSD1_BUS_EMMCSDSS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_MMCSD1,
        TISCI_DEV_MMCSD1_BUS_EMMCSDSS_XIN_CLK,
        0
    },
    {
        TISCI_DEV_EQEP0,
        TISCI_DEV_EQEP0_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_EQEP1,
        TISCI_DEV_EQEP1_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_EQEP2,
        TISCI_DEV_EQEP2_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_ESM0,
        TISCI_DEV_ESM0_BUS_CLK,
        0
    },
    {
        TISCI_DEV_MCU_ESM0,
        TISCI_DEV_MCU_ESM0_BUS_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_ESM0,
        TISCI_DEV_WKUP_ESM0_BUS_CLK,
        0
    },
    {
        TISCI_DEV_GIC0,
        TISCI_DEV_GIC0_BUS_VCLK_CLK,
        0
    },
    {
        TISCI_DEV_GPIO0,
        TISCI_DEV_GPIO0_BUS_MMR_CLK,
        0
    },
    {
        TISCI_DEV_GPIO1,
        TISCI_DEV_GPIO1_BUS_MMR_CLK,
        0
    },
    /*From MCU_SYSCLK0*/
    {
        TISCI_DEV_WKUP_GPIO0,
        TISCI_DEV_WKUP_GPIO0_BUS_MMR_CLK,
        100000000
    },
#if 0
    /* This combination does not work. It is known issue:
     * Description:
     * In the firmware the WKUP PLL CTRL PLLDIV (register 0x42010000 + 0x118) value seems
     * to be not writable (even after KICK registers are modified).
     * The effect is the divider is fixed to 1 and output clock is 400 MHz.
     */
    {
        TISCI_DEV_WKUP_GPIO0,
        TISCI_DEV_WKUP_GPIO0_BUS_MMR_CLK,
        12500000
    },
#endif
    {
        TISCI_DEV_WKUP_GPIO0,
        TISCI_DEV_WKUP_GPIO0_BUS_MMR_CLK,
        32000
    },
    {
        TISCI_DEV_GPMC0,
        TISCI_DEV_GPMC0_BUS_FUNC_CLK,
        150000000
    },
    {
        TISCI_DEV_GPMC0,
        TISCI_DEV_GPMC0_BUS_PI_GPMC_RET_CLK,
        0
    },
    {
        TISCI_DEV_GPMC0,
        TISCI_DEV_GPMC0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_GPMC0,
        TISCI_DEV_GPMC0_BUS_PO_GPMC_DEV_CLK,
        0
    },
    {
        TISCI_DEV_GTC0,
        TISCI_DEV_GTC0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_RGMII_MHZ_5_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_WIZ1_TX_SLV_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_WIZ0_RX_SLV_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_VCLK_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_UCLK_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_WIZ0_TX_SLV_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_WIZ1_RX_SLV_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_PR1_RGMII1_RXC_I,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_RGMII_MHZ_250_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_RGMII_MHZ_50_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_IEP_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_CORE_CLK,
        225000000
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_CORE_CLK,
        250000000
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_PR1_RGMII0_RXC_I,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_PR1_RGMII1_TXC_I,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG0,
        TISCI_DEV_PRU_ICSSG0_BUS_PR1_RGMII0_TXC_I,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_RGMII_MHZ_5_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_WIZ1_TX_SLV_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_WIZ0_RX_SLV_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_VCLK_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_UCLK_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_WIZ0_TX_SLV_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_WIZ1_RX_SLV_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_PR1_RGMII1_RXC_I,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_RGMII_MHZ_250_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_RGMII_MHZ_50_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_IEP_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_CORE_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_PR1_RGMII0_RXC_I,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_PR1_RGMII1_TXC_I,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG1,
        TISCI_DEV_PRU_ICSSG1_BUS_PR1_RGMII0_TXC_I,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_RGMII_MHZ_5_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_WIZ1_TX_SLV_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_WIZ0_RX_SLV_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_VCLK_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_UCLK_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_WIZ0_TX_SLV_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_WIZ1_RX_SLV_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_PR1_RGMII1_RXC_I,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_RGMII_MHZ_250_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_RGMII_MHZ_50_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_IEP_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_CORE_CLK,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_PR1_RGMII0_RXC_I,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_PR1_RGMII1_TXC_I,
        0
    },
    {
        TISCI_DEV_PRU_ICSSG2,
        TISCI_DEV_PRU_ICSSG2_BUS_PR1_RGMII0_TXC_I,
        0
    },
    {
        TISCI_DEV_GPU0,
        TISCI_DEV_GPU0_BUS_MEM_CLK,
        0
    },
    {
        TISCI_DEV_GPU0,
        TISCI_DEV_GPU0_BUS_HYD_CORE_CLK,
        0
    },
    {
        TISCI_DEV_GPU0,
        TISCI_DEV_GPU0_BUS_SGX_CORE_CLK,
        0
    },
    {
        TISCI_DEV_GPU0,
        TISCI_DEV_GPU0_BUS_SYS_CLK,
        0
    },
    {
        TISCI_DEV_CCDEBUGSS0,
        TISCI_DEV_CCDEBUGSS0_BUS_ATB1_CLK,
        0
    },
    {
        TISCI_DEV_CCDEBUGSS0,
        TISCI_DEV_CCDEBUGSS0_BUS_ATB0_CLK,
        0
    },
    {
        TISCI_DEV_CCDEBUGSS0,
        TISCI_DEV_CCDEBUGSS0_BUS_SYS_CLK,
        0
    },
    {
        TISCI_DEV_CCDEBUGSS0,
        TISCI_DEV_CCDEBUGSS0_BUS_DBG_CLK,
        0
    },
    {
        TISCI_DEV_CCDEBUGSS0,
        TISCI_DEV_CCDEBUGSS0_BUS_CFG_CLK,
        0
    },
    /* TODO */
    {
        TISCI_DEV_DSS0,
        TISCI_DEV_DSS0_BUS_DPI_0_IN_CLK_BUS_IN1_CLOCKDIVIDER_DSS_BUS_OUT0,
        0
    },
    {
        TISCI_DEV_DSS0,
        TISCI_DEV_DSS0_BUS_DSS_FUNC_CLK,
        0
    },
    {
        TISCI_DEV_DSS0,
        TISCI_DEV_DSS0_BUS_DPI_1_IN_CLK,
        0
    },
    {
        TISCI_DEV_DSS0,
        TISCI_DEV_DSS0_BUS_DPI_0_IN_CLK_BUS_IN0_CLOCKDIVIDER_DSS_BUS_OUT0,
        0
    },
    {
        TISCI_DEV_DSS0,
        TISCI_DEV_DSS0_BUS_DPI_1_OUT_CLK,
        0
    },
    {
        TISCI_DEV_DEBUGSS0,
        TISCI_DEV_DEBUGSS0_BUS_ATB1_CLK,
        0
    },
    {
        TISCI_DEV_DEBUGSS0,
        TISCI_DEV_DEBUGSS0_BUS_ATB5_CLK,
        0
    },
    {
        TISCI_DEV_DEBUGSS0,
        TISCI_DEV_DEBUGSS0_BUS_ATB0_CLK,
        0
    },
    {
        TISCI_DEV_DEBUGSS0,
        TISCI_DEV_DEBUGSS0_BUS_SYS_CLK,
        0
    },
    {
        TISCI_DEV_DEBUGSS0,
        TISCI_DEV_DEBUGSS0_BUS_ATB4_CLK,
        0
    },
    {
        TISCI_DEV_DEBUGSS0,
        TISCI_DEV_DEBUGSS0_BUS_CFG_CLK,
        0
    },
    {
        TISCI_DEV_DEBUGSS0,
        TISCI_DEV_DEBUGSS0_BUS_ATB2_CLK,
        0
    },
    {
        TISCI_DEV_DEBUGSS0,
        TISCI_DEV_DEBUGSS0_BUS_DBG_CLK,
        0
    },
    {
        TISCI_DEV_DEBUGSS0,
        TISCI_DEV_DEBUGSS0_BUS_ATB3_CLK,
        0
    },
    {
        TISCI_DEV_EFUSE0,
        TISCI_DEV_EFUSE0_BUS_VBUSP_PLL_CLK_CLK,
        0
    },
    {
        TISCI_DEV_EFUSE0,
        TISCI_DEV_EFUSE0_BUS_EFC1_CTL_FCLK,
        0
    },
    {
        TISCI_DEV_EFUSE0,
        TISCI_DEV_EFUSE0_BUS_EFC0_CTL_FCLK,
        0
    },
    {
        TISCI_DEV_PSC0,
        TISCI_DEV_PSC0_BUS_CLK,
        0
    },
    {
        TISCI_DEV_PSC0,
        TISCI_DEV_PSC0_BUS_SLOW_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DEBUGSS0,
        TISCI_DEV_MCU_DEBUGSS0_BUS_ATB1_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DEBUGSS0,
        TISCI_DEV_MCU_DEBUGSS0_BUS_ATB0_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DEBUGSS0,
        TISCI_DEV_MCU_DEBUGSS0_BUS_SYS_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DEBUGSS0,
        TISCI_DEV_MCU_DEBUGSS0_BUS_CFG_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DEBUGSS0,
        TISCI_DEV_MCU_DEBUGSS0_BUS_ATB2_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DEBUGSS0,
        TISCI_DEV_MCU_DEBUGSS0_BUS_DBG_CLK,
        0
    },
    {
        TISCI_DEV_MCU_DEBUGSS0,
        TISCI_DEV_MCU_DEBUGSS0_BUS_ATB3_CLK,
        0
    },
    {
        TISCI_DEV_MCU_EFUSE0,
        TISCI_DEV_MCU_EFUSE0_BUS_VBUSP_CLK_CLK,
        0
    },
    {
        TISCI_DEV_MCU_EFUSE0,
        TISCI_DEV_MCU_EFUSE0_BUS_EFC3_CTL_FCLK,
        0
    },
    {
        TISCI_DEV_MCU_EFUSE0,
        TISCI_DEV_MCU_EFUSE0_BUS_EFC0_CTL_FCLK,
        0
    },
    {
        TISCI_DEV_MCU_EFUSE0,
        TISCI_DEV_MCU_EFUSE0_BUS_EFC1_CTL_FCLK,
        0
    },
    {
        TISCI_DEV_MCU_EFUSE0,
        TISCI_DEV_MCU_EFUSE0_BUS_EFC2_CTL_FCLK,
        0
    },
    {
        TISCI_DEV_PBIST0,
        TISCI_DEV_PBIST0_BUS_CLK1_CLK,
        0
    },
    {
        TISCI_DEV_PBIST0,
        TISCI_DEV_PBIST0_BUS_CLK4_CLK,
        0
    },
    {
        TISCI_DEV_PBIST0,
        TISCI_DEV_PBIST0_BUS_CLK2_CLK,
        0
    },
    {
        TISCI_DEV_PBIST1,
        TISCI_DEV_PBIST1_BUS_CLK1_CLK,
        0
    },
    {
        TISCI_DEV_PBIST1,
        TISCI_DEV_PBIST1_BUS_CLK4_CLK,
        0
    },
    {
        TISCI_DEV_PBIST1,
        TISCI_DEV_PBIST1_BUS_CLK2_CLK,
        0
    },
    {
        TISCI_DEV_MCU_PBIST0,
        TISCI_DEV_MCU_PBIST0_BUS_CLK1_CLK,
        0
    },
    {
        TISCI_DEV_MCU_PBIST0,
        TISCI_DEV_MCU_PBIST0_BUS_CLK4_CLK,
        0
    },
    {
        TISCI_DEV_MCU_PBIST0,
        TISCI_DEV_MCU_PBIST0_BUS_CLK2_CLK,
        0
    },
    {
        TISCI_DEV_PLLCTRL0,
        TISCI_DEV_PLLCTRL0_BUS_VBUS_SLV_REFCLK_CLK,
        0
    },
    {
        TISCI_DEV_PLLCTRL0,
        TISCI_DEV_PLLCTRL0_BUS_PLL_CLKOUT_CLK,
        0
    },
    {
        TISCI_DEV_PLLCTRL0,
        TISCI_DEV_PLLCTRL0_BUS_PLL_REFCLK_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_PLLCTRL0,
        TISCI_DEV_WKUP_PLLCTRL0_BUS_VBUS_SLV_REFCLK_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_PLLCTRL0,
        TISCI_DEV_WKUP_PLLCTRL0_BUS_PLL_CLKOUT_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_PLLCTRL0,
        TISCI_DEV_WKUP_PLLCTRL0_BUS_PLL_REFCLK_CLK,
        0
    },
    {
        TISCI_DEV_MCU_ROM0,
        TISCI_DEV_MCU_ROM0_BUS_CLK_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_PSC0,
        TISCI_DEV_WKUP_PSC0_BUS_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_PSC0,
        TISCI_DEV_WKUP_PSC0_BUS_SLOW_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_VTM0,
        TISCI_DEV_WKUP_VTM0_BUS_FIX_REF_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_VTM0,
        TISCI_DEV_WKUP_VTM0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_DEBUGSUSPENDRTR0,
        TISCI_DEV_DEBUGSUSPENDRTR0_BUS_INTR_CLK,
        0
    },
    {
        TISCI_DEV_CBASS0,
        TISCI_DEV_CBASS0_BUS_MAIN_SYSCLK0_2_CLK,
        0
    },
    {
        TISCI_DEV_CBASS0,
        TISCI_DEV_CBASS0_BUS_MAIN_SYSCLK0_4_CLK,
        0
    },
    {
        TISCI_DEV_CBASS_DEBUG0,
        TISCI_DEV_CBASS_DEBUG0_BUS_MAIN_SYSCLK0_2_CLK,
        0
    },
    {
        TISCI_DEV_CBASS_DEBUG0,
        TISCI_DEV_CBASS_DEBUG0_BUS_MAIN_SYSCLK0_4_CLK,
        0
    },
    {
        TISCI_DEV_CBASS_FW0,
        TISCI_DEV_CBASS_FW0_BUS_MAIN_SYSCLK0_2_CLK,
        0
    },
    {
        TISCI_DEV_CBASS_FW0,
        TISCI_DEV_CBASS_FW0_BUS_MAIN_SYSCLK0_4_CLK,
        0
    },
    {
        TISCI_DEV_CBASS_INFRA0,
        TISCI_DEV_CBASS_INFRA0_BUS_GTC_CLOCK_1_CLK,
        0
    },
    {
        TISCI_DEV_CBASS_INFRA0,
        TISCI_DEV_CBASS_INFRA0_BUS_MAIN_SYSCLK0_2_CLK,
        0
    },
    {
        TISCI_DEV_CBASS_INFRA0,
        TISCI_DEV_CBASS_INFRA0_BUS_MAIN_SYSCLK0_4_CLK,
        0
    },
    {
        TISCI_DEV_ECC_AGGR0,
        TISCI_DEV_ECC_AGGR0_BUS_AGGR_CLK,
        0
    },
    {
        TISCI_DEV_ECC_AGGR1,
        TISCI_DEV_ECC_AGGR1_BUS_AGGR_CLK,
        0
    },
    {
        TISCI_DEV_ECC_AGGR2,
        TISCI_DEV_ECC_AGGR2_BUS_AGGR_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CBASS0,
        TISCI_DEV_MCU_CBASS0_BUS_MCU_SYSCLK0_8_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CBASS0,
        TISCI_DEV_MCU_CBASS0_BUS_MCU_SYSCLK0_4_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CBASS0,
        TISCI_DEV_MCU_CBASS0_BUS_MCU_SYSCLK0_2_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CBASS_DEBUG0,
        TISCI_DEV_MCU_CBASS_DEBUG0_BUS_MCU_SYSCLK0_2_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CBASS_FW0,
        TISCI_DEV_MCU_CBASS_FW0_BUS_MCU_SYSCLK0_4_CLK,
        0
    },
    {
        TISCI_DEV_MCU_CBASS_FW0,
        TISCI_DEV_MCU_CBASS_FW0_BUS_MCU_SYSCLK0_2_CLK,
        0
    },
    {
        TISCI_DEV_MCU_ECC_AGGR0,
        TISCI_DEV_MCU_ECC_AGGR0_BUS_AGGR_CLK,
        0
    },
    {
        TISCI_DEV_MCU_ECC_AGGR1,
        TISCI_DEV_MCU_ECC_AGGR1_BUS_AGGR_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_CBASS0,
        TISCI_DEV_WKUP_CBASS0_BUS_WKUP_MCU_PLL_OUT_2_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_CBASS0,
        TISCI_DEV_WKUP_CBASS0_BUS_WKUP_MCU_PLL_OUT_4_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_ECC_AGGR0,
        TISCI_DEV_WKUP_ECC_AGGR0_BUS_AGGR_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_CBASS_FW0,
        TISCI_DEV_WKUP_CBASS_FW0_BUS_WKUP_MCU_PLL_OUT_2_CLK,
        0
    },
    {
        TISCI_DEV_MAIN2MCU_LVL_INTRTR0,
        TISCI_DEV_MAIN2MCU_LVL_INTRTR0_BUS_INTR_CLK,
        0
    },
    {
        TISCI_DEV_MAIN2MCU_PLS_INTRTR0,
        TISCI_DEV_MAIN2MCU_PLS_INTRTR0_BUS_INTR_CLK,
        0
    },
    {
        TISCI_DEV_CTRL_MMR0,
        TISCI_DEV_CTRL_MMR0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_GPIOMUX_INTRTR0,
        TISCI_DEV_GPIOMUX_INTRTR0_BUS_INTR_CLK,
        0
    },
    {
        TISCI_DEV_PLL_MMR0,
        TISCI_DEV_PLL_MMR0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCU_MCAN0,
        TISCI_DEV_MCU_MCAN0_BUS_MCANSS_CCLK_CLK,
        80000000
    },
    {
        TISCI_DEV_MCU_MCAN0,
        TISCI_DEV_MCU_MCAN0_BUS_MCANSS_HCLK_CLK,
        0
    },
    {
        TISCI_DEV_MCU_MCAN1,
        TISCI_DEV_MCU_MCAN1_BUS_MCANSS_CCLK_CLK,
        80000000
    },
    {
        TISCI_DEV_MCU_MCAN1,
        TISCI_DEV_MCU_MCAN1_BUS_MCANSS_HCLK_CLK,
        0
    },
    /*Default for TISCI_DEV_MCASP0_BUS_AUX_CLK is from HFOSC1_CLKOUT.
    * This provides clock isolation between Main and WKUP/MCU . */
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_AUX_CLK,
        25000000
    },
    /* The following freqs for TISCI_DEV_MCASP0_BUS_AUX_CLK are to test
    * the programmable 4bit DIV after ARM1_PLL_CLKOUT*/
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_AUX_CLK,
        200000000
    },
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_AUX_CLK,
        400000000
    },
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_AUX_CLK,
        800000000
    },
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_AUX_CLK,
        50000000
    },
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_MCASP_AHCLKX_PIN,
        0
    },
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_MCASP_AHCLKR_PIN,
        0
    },
    /*Default for TISCI_DEV_MCASP0_BUS_AUX_CLK is from HFOSC1_CLKOUT.
    * This provides clock isolation between Main and WKUP/MCU . */
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_AUX_CLK,
        25000000
    },
    /* The following freqs for TISCI_DEV_MCASP0_BUS_AUX_CLK are to test
    * the programmable 4bit DIV after ARM1_PLL_CLKOUT*/
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_AUX_CLK,
        200000000
    },
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_AUX_CLK,
        400000000
    },
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_AUX_CLK,
        800000000
    },
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_AUX_CLK,
        50000000
    },
    {
        TISCI_DEV_MCASP1,
        TISCI_DEV_MCASP1_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCASP1,
        TISCI_DEV_MCASP1_BUS_MCASP_AHCLKX_PIN,
        0
    },
    {
        TISCI_DEV_MCASP1,
        TISCI_DEV_MCASP1_BUS_MCASP_AHCLKR_PIN,
        0
    },
    /*Default for TISCI_DEV_MCASP0_BUS_AUX_CLK is from HFOSC1_CLKOUT.
    * This provides clock isolation between Main and WKUP/MCU . */
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_AUX_CLK,
        25000000
    },
    /* The following freqs for TISCI_DEV_MCASP0_BUS_AUX_CLK are to test
    * the programmable 4bit DIV after ARM1_PLL_CLKOUT*/
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_AUX_CLK,
        200000000
    },
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_AUX_CLK,
        400000000
    },
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP0_BUS_AUX_CLK,
        800000000
    },
    {
        TISCI_DEV_MCASP0,
        TISCI_DEV_MCASP1_BUS_AUX_CLK,
        50000000
    },
    {
        TISCI_DEV_MCASP2,
        TISCI_DEV_MCASP2_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCASP2,
        TISCI_DEV_MCASP2_BUS_MCASP_AHCLKX_PIN,
        0
    },
    {
        TISCI_DEV_MCASP2,
        TISCI_DEV_MCASP2_BUS_MCASP_AHCLKR_PIN,
        0
    },
    {
        TISCI_DEV_MCU_CTRL_MMR0,
        TISCI_DEV_MCU_CTRL_MMR0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCU_PLL_MMR0,
        TISCI_DEV_MCU_PLL_MMR0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCU_SEC_MMR0,
        TISCI_DEV_MCU_SEC_MMR0_BUS_VBUSP_CLK,
        0
    },
    /*TODO: I2C tests are failing */
    {
        TISCI_DEV_I2C0,
        TISCI_DEV_I2C0_BUS_CLK,
        0
    },
    {
        TISCI_DEV_I2C0,
        TISCI_DEV_I2C0_BUS_PISYS_CLK,
        0
    },
    {
        TISCI_DEV_I2C1,
        TISCI_DEV_I2C1_BUS_CLK,
        0
    },
    {
        TISCI_DEV_I2C1,
        TISCI_DEV_I2C1_BUS_PISYS_CLK,
        0
    },
    {
        TISCI_DEV_I2C2,
        TISCI_DEV_I2C2_BUS_CLK,
        0
    },
    {
        TISCI_DEV_I2C2,
        TISCI_DEV_I2C2_BUS_PISYS_CLK,
        0
    },
    {
        TISCI_DEV_I2C3,
        TISCI_DEV_I2C3_BUS_CLK,
        0
    },
    {
        TISCI_DEV_I2C3,
        TISCI_DEV_I2C3_BUS_PISYS_CLK,
        0
    },
    {
        TISCI_DEV_MCU_I2C0,
        TISCI_DEV_MCU_I2C0_BUS_CLK,
        0
    },
    {
        TISCI_DEV_MCU_I2C0,
        TISCI_DEV_MCU_I2C0_BUS_PISYS_CLK,
        96000000
    },
    {
        TISCI_DEV_WKUP_I2C0,
        TISCI_DEV_WKUP_I2C0_BUS_PISYS_CLK,
        96000000
    },
    {
        TISCI_DEV_WKUP_I2C0,
        TISCI_DEV_WKUP_I2C0_BUS_PISYS_CLK,
        25000000
    },
    {
        TISCI_DEV_WKUP_I2C0,
        TISCI_DEV_WKUP_I2C0_BUS_CLK,
        /*MCU_SYSCLK0[200/400 MHz]/4*/
        100000000
    },
    {
        TISCI_DEV_MCU_MSRAM0,
        TISCI_DEV_MCU_MSRAM0_BUS_CCLK_CLK,
        0
    },
    {
        TISCI_DEV_MCU_MSRAM0,
        TISCI_DEV_MCU_MSRAM0_BUS_VCLK_CLK,
        0
    },
    {
        TISCI_DEV_DFTSS0,
        TISCI_DEV_DFTSS0_BUS_VBUSP_CLK_CLK,
        0
    },
    /* The inputs for cpts_rclk from NAVSS_CPTS_RCLK_MUX are segregated
    * TODO: See how to select one of them .*/
    {
        TISCI_DEV_NAVSS0,
        TISCI_DEV_NAVSS0_BUS_UDMASS_VD2CLK,
        0
    },
    {
        TISCI_DEV_NAVSS0,
        TISCI_DEV_NAVSS0_BUS_ICSS_G2CLK,
        0
    },
    {
        TISCI_DEV_NAVSS0,
        TISCI_DEV_NAVSS0_BUS_ICSS_G0CLK,
        0
    },
    {
        TISCI_DEV_NAVSS0,
        TISCI_DEV_NAVSS0_BUS_MSMC0CLK,
        0
    },
    {
        TISCI_DEV_NAVSS0,
        TISCI_DEV_NAVSS0_BUS_RCLK_BUS_IN0_ADPLLM_HSDIV_WRAP_MCU_1_BUS_HSDIV_CLKOUT2_CLK,
        0
    },
    {
        TISCI_DEV_NAVSS0,
        TISCI_DEV_NAVSS0_BUS_MODSS_VD2CLK,
        0
    },
    {
        TISCI_DEV_NAVSS0,
        TISCI_DEV_NAVSS0_BUS_PDMA_MAIN1CLK,
        0
    },
    {
        TISCI_DEV_NAVSS0,
        TISCI_DEV_NAVSS0_BUS_NBSS_VCLK,
        0
    },
    {
        TISCI_DEV_NAVSS0,
        TISCI_DEV_NAVSS0_BUS_RCLK_BUS_IN1_ADPLLLJM_HSDIV_WRAP_MAIN_0_BUS_HSDIV_CLKOUT3_CLK,
        0
    },
    {
        TISCI_DEV_NAVSS0,
        TISCI_DEV_NAVSS0_BUS_NBSS_VD2CLK,
        0
    },
    {
        TISCI_DEV_NAVSS0,
        TISCI_DEV_NAVSS0_BUS_ICSS_G1CLK,
        0
    },
    {
        TISCI_DEV_MCU_NAVSS0,
        TISCI_DEV_MCU_NAVSS0_BUS_UDMASS_VD2CLK,
        0
    },
    {
        TISCI_DEV_MCU_NAVSS0,
        TISCI_DEV_MCU_NAVSS0_BUS_CPSW0CLK,
        0
    },
    {
        TISCI_DEV_MCU_NAVSS0,
        TISCI_DEV_MCU_NAVSS0_BUS_MODSS_VD2CLK,
        0
    },
    {
        TISCI_DEV_MCU_NAVSS0,
        TISCI_DEV_MCU_NAVSS0_BUS_PDMA_MCU1CLK,
        0
    },
    {
        TISCI_DEV_PCIE0,
        TISCI_DEV_PCIE0_BUS_PCIE_CBA_CLK,
        0
    },
    {
        TISCI_DEV_PCIE0,
        TISCI_DEV_PCIE0_BUS_PCIE_TXI0_CLK,
        0
    },
    {
        TISCI_DEV_PCIE0,
        TISCI_DEV_PCIE0_BUS_PCIE_CPTS_RCLK_CLK_BUS_IN1_ADPLLLJM_HSDIV_WRAP_MAIN_0_BUS_HSDIV_CLKOUT3_CLK,
        0
    },
    {
        TISCI_DEV_PCIE0,
        TISCI_DEV_PCIE0_BUS_PCIE_CPTS_RCLK_CLK_BUS_IN0_ADPLLM_HSDIV_WRAP_MCU_1_BUS_HSDIV_CLKOUT2_CLK,
        0
    },
    {
        TISCI_DEV_PCIE0,
        TISCI_DEV_PCIE0_BUS_PCIE_TXR1_CLK,
        0
    },
    {
        TISCI_DEV_PCIE0,
        TISCI_DEV_PCIE0_BUS_PCIE_TXR0_CLK,
        0
    },
    {
        TISCI_DEV_PCIE1,
        TISCI_DEV_PCIE1_BUS_PCIE_CBA_CLK,
        0
    },
    {
        TISCI_DEV_PCIE1,
        TISCI_DEV_PCIE1_BUS_PCIE_TXI0_CLK,
        0
    },
    {
        TISCI_DEV_PCIE1,
        TISCI_DEV_PCIE1_BUS_PCIE_CPTS_RCLK_CLK_BUS_IN1_ADPLLLJM_HSDIV_WRAP_MAIN_0_BUS_HSDIV_CLKOUT3_CLK,
        0
    },
    {
        TISCI_DEV_PCIE1,
        TISCI_DEV_PCIE1_BUS_PCIE_CPTS_RCLK_CLK_BUS_IN0_ADPLLM_HSDIV_WRAP_MCU_1_BUS_HSDIV_CLKOUT2_CLK,
        0
    },
    {
        TISCI_DEV_PCIE1,
        TISCI_DEV_PCIE1_BUS_PCIE_TXR0_CLK,
        0
    },
    {
        TISCI_DEV_PDMA_DEBUG0,
        TISCI_DEV_PDMA_DEBUG0_BUS_VCLK,
        0
    },
    {
        TISCI_DEV_PDMA0,
        TISCI_DEV_PDMA0_BUS_VCLK,
        0
    },
    {
        TISCI_DEV_PDMA1,
        TISCI_DEV_PDMA1_BUS_VCLK,
        0
    },
    {
        TISCI_DEV_MCU_PDMA0,
        TISCI_DEV_MCU_PDMA0_BUS_VCLK,
        0
    },
    {
        TISCI_DEV_MCU_PDMA1,
        TISCI_DEV_MCU_PDMA1_BUS_VCLK,
        0
    },
    {
        TISCI_DEV_MCU_PSRAM0,
        TISCI_DEV_MCU_PSRAM0_BUS_CLK_CLK,
        0
    },
    {
        TISCI_DEV_PSRAMECC0,
        TISCI_DEV_PSRAMECC0_BUS_CLK_CLK,
        0
    },
    {
        TISCI_DEV_MCU_ARMSS0,
        TISCI_DEV_MCU_ARMSS0_BUS_INTERFACE_CLK,
        0
    },
    {
        TISCI_DEV_MCU_ARMSS0,
        TISCI_DEV_MCU_ARMSS0_CPU0_BUS_INTERFACE_CLK,
        0
    },
    {
        TISCI_DEV_MCU_ARMSS0,
        TISCI_DEV_MCU_ARMSS0_CPU0_BUS_INTERFACE_PHASE,
        0
    },
    {
        TISCI_DEV_MCU_ARMSS0,
        TISCI_DEV_MCU_ARMSS0_CPU0_BUS_CPU_CLK,
        0
    },
    {
        TISCI_DEV_MCU_ARMSS0,
        TISCI_DEV_MCU_ARMSS0_CPU1_BUS_INTERFACE_CLK,
        0
    },
    {
        TISCI_DEV_MCU_ARMSS0,
        TISCI_DEV_MCU_ARMSS0_CPU1_BUS_CPU_CLK,
        0
    },
    /* RTI == WWDT*/
    {
        TISCI_DEV_RTI0,
        TISCI_DEV_RTI0_BUS_RTI_CLK,
        25000000
    },
    {
        TISCI_DEV_RTI0,
        TISCI_DEV_RTI0_BUS_RTI_CLK,
        12500000
    },
    {
        TISCI_DEV_RTI0,
        TISCI_DEV_RTI0_BUS_RTI_CLK,
        32000
    },
    {
        TISCI_DEV_RTI0,
        TISCI_DEV_RTI0_BUS_RTI_CLK,
        32000
    },
    {
        TISCI_DEV_RTI0,
        TISCI_DEV_RTI0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_RTI1,
        TISCI_DEV_RTI1_BUS_RTI_CLK,
        25000000
    },
    {
        TISCI_DEV_RTI1,
        TISCI_DEV_RTI1_BUS_RTI_CLK,
        12500000
    },
    {
        TISCI_DEV_RTI1,
        TISCI_DEV_RTI1_BUS_RTI_CLK,
        32000
    },
    {
        TISCI_DEV_RTI1,
        TISCI_DEV_RTI1_BUS_RTI_CLK,
        32000
    },
    {
        TISCI_DEV_RTI1,
        TISCI_DEV_RTI1_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_RTI2,
        TISCI_DEV_RTI2_BUS_RTI_CLK,
        25000000
    },
    {
        TISCI_DEV_RTI2,
        TISCI_DEV_RTI2_BUS_RTI_CLK,
        12500000
    },
    {
        TISCI_DEV_RTI2,
        TISCI_DEV_RTI2_BUS_RTI_CLK,
        32000
    },
    {
        TISCI_DEV_RTI2,
        TISCI_DEV_RTI2_BUS_RTI_CLK,
        32000
    },
    {
        TISCI_DEV_RTI2,
        TISCI_DEV_RTI2_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_RTI3,
        TISCI_DEV_RTI3_BUS_RTI_CLK,
        25000000
    },
    {
        TISCI_DEV_RTI3,
        TISCI_DEV_RTI3_BUS_RTI_CLK,
        12500000
    },
    {
        TISCI_DEV_RTI3,
        TISCI_DEV_RTI3_BUS_RTI_CLK,
        32000
    },
    {
        TISCI_DEV_RTI3,
        TISCI_DEV_RTI3_BUS_RTI_CLK,
        32000
    },
    {
        TISCI_DEV_RTI3,
        TISCI_DEV_RTI3_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCU_RTI0,
        TISCI_DEV_MCU_RTI0_BUS_RTI_CLK,
        25000000
    },
    {
        TISCI_DEV_MCU_RTI0,
        TISCI_DEV_MCU_RTI0_BUS_RTI_CLK,
        32000
    },
    {
        TISCI_DEV_MCU_RTI0,
        TISCI_DEV_MCU_RTI0_BUS_RTI_CLK,
        12500000
    },
    {
        TISCI_DEV_MCU_RTI0,
        TISCI_DEV_MCU_RTI0_BUS_RTI_CLK,
        32000
    },
    {
        TISCI_DEV_MCU_RTI0,
        TISCI_DEV_MCU_RTI0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCU_RTI1,
        TISCI_DEV_MCU_RTI1_BUS_RTI_CLK,
        25000000
    },
    {
        TISCI_DEV_MCU_RTI1,
        TISCI_DEV_MCU_RTI1_BUS_RTI_CLK,
        32000
    },
    {
        TISCI_DEV_MCU_RTI1,
        TISCI_DEV_MCU_RTI1_BUS_RTI_CLK,
        12500000
    },
    {
        TISCI_DEV_MCU_RTI1,
        TISCI_DEV_MCU_RTI1_BUS_RTI_CLK,
        32000
    },
    {
        TISCI_DEV_MCU_RTI1,
        TISCI_DEV_MCU_RTI1_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_SA2_UL0,
        TISCI_DEV_SA2_UL0_BUS_PKA_IN_CLK,
        0
    },
    {
        TISCI_DEV_SA2_UL0,
        TISCI_DEV_SA2_UL0_BUS_X1_CLK,
        0
    },
    {
        TISCI_DEV_SA2_UL0,
        TISCI_DEV_SA2_UL0_BUS_X2_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI0,
        TISCI_DEV_MCSPI0_BUS_IO_CLKSPII_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI0,
        TISCI_DEV_MCSPI0_BUS_CLKSPIREF_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI0,
        TISCI_DEV_MCSPI0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI0,
        TISCI_DEV_MCSPI0_BUS_IO_CLKSPIO_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI1,
        TISCI_DEV_MCSPI1_BUS_IO_CLKSPII_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI1,
        TISCI_DEV_MCSPI1_BUS_CLKSPIREF_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI1,
        TISCI_DEV_MCSPI1_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI1,
        TISCI_DEV_MCSPI1_BUS_IO_CLKSPIO_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI2,
        TISCI_DEV_MCSPI2_BUS_IO_CLKSPII_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI2,
        TISCI_DEV_MCSPI2_BUS_CLKSPIREF_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI2,
        TISCI_DEV_MCSPI2_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI2,
        TISCI_DEV_MCSPI2_BUS_IO_CLKSPIO_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI3,
        TISCI_DEV_MCSPI3_BUS_IO_CLKSPII_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI3,
        TISCI_DEV_MCSPI3_BUS_CLKSPIREF_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI3,
        TISCI_DEV_MCSPI3_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI3,
        TISCI_DEV_MCSPI3_BUS_IO_CLKSPIO_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI4,
        TISCI_DEV_MCSPI4_BUS_CLKSPIREF_CLK,
        0
    },
    {
        TISCI_DEV_MCSPI4,
        TISCI_DEV_MCSPI4_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCU_MCSPI0,
        TISCI_DEV_MCU_MCSPI0_BUS_IO_CLKSPII_CLK,
        0
    },
    {
        TISCI_DEV_MCU_MCSPI0,
        TISCI_DEV_MCU_MCSPI0_BUS_CLKSPIREF_CLK,
        0
    },
    {
        TISCI_DEV_MCU_MCSPI0,
        TISCI_DEV_MCU_MCSPI0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCU_MCSPI0,
        TISCI_DEV_MCU_MCSPI0_BUS_IO_CLKSPIO_CLK,
        0
    },
    {
        TISCI_DEV_MCU_MCSPI1,
        TISCI_DEV_MCU_MCSPI1_BUS_IO_CLKSPII_CLK,
        0
    },
    {
        TISCI_DEV_MCU_MCSPI1,
        TISCI_DEV_MCU_MCSPI1_BUS_CLKSPIREF_CLK,
        0
    },
    {
        TISCI_DEV_MCU_MCSPI1,
        TISCI_DEV_MCU_MCSPI1_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCU_MCSPI1,
        TISCI_DEV_MCU_MCSPI1_BUS_IO_CLKSPIO_CLK,
        0
    },
    {
        TISCI_DEV_MCU_MCSPI2,
        TISCI_DEV_MCU_MCSPI2_BUS_CLKSPIREF_CLK,
        0
    },
    {
        TISCI_DEV_MCU_MCSPI2,
        TISCI_DEV_MCU_MCSPI2_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_TIMESYNC_INTRTR0,
        TISCI_DEV_TIMESYNC_INTRTR0_BUS_INTR_CLK,
        0
    },
    {
        TISCI_DEV_UART0,
        TISCI_DEV_UART0_BUS_FCLK_CLK,
        0
    },
    {
        TISCI_DEV_UART0,
        TISCI_DEV_UART0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_UART1,
        TISCI_DEV_UART1_BUS_FCLK_CLK,
        0
    },
    {
        TISCI_DEV_UART1,
        TISCI_DEV_UART1_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_UART2,
        TISCI_DEV_UART2_BUS_FCLK_CLK,
        0
    },
    {
        TISCI_DEV_UART2,
        TISCI_DEV_UART2_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_MCU_UART0,
        TISCI_DEV_MCU_UART0_BUS_FCLK_CLK,
        96000000
    },
    {
        TISCI_DEV_MCU_UART0,
        TISCI_DEV_MCU_UART0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_UART0,
        TISCI_DEV_WKUP_UART0_BUS_FCLK_CLK,
        25000000
    },
    {
        TISCI_DEV_WKUP_UART0,
        TISCI_DEV_WKUP_UART0_BUS_FCLK_CLK,
        96000000
    },
#if 0
    /* Known Issue:
     * The WKUP USART0 fclk can be sourced from HFOSC0_CLKOUT or
     * MCUHSDIV_CLKOUT3 or PER0_PLL_CLKOUT_DIV5. The mux output of
     * CLK_AM6_CLOCKMUX_WKUPUSART_CLK_SEL_BUS_OUT0 is marked as not
     * modifiable.
     * This disallows setting variations of MCUHSDIV_CLKOUT3 or
     * PER0_PLL_CLKOUT_DIV5.
     */
    {
        TISCI_DEV_WKUP_UART0,
        TISCI_DEV_WKUP_UART0_BUS_FCLK_CLK,
        48000000
    },
#endif
    {
        TISCI_DEV_WKUP_UART0,
        TISCI_DEV_WKUP_UART0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_USB3SS0,
        TISCI_DEV_USB3SS0_BUS_SUSP_CLK,
        0
    },
    {
        TISCI_DEV_USB3SS0,
        TISCI_DEV_USB3SS0_BUS_PHY2_REFCLK960M_CLK,
        0
    },
    /* Default for USB0_REF_CLK_SEl is from MAIN_PLL_REF_CLK */
    {
        TISCI_DEV_USB3SS0,
        TISCI_DEV_USB3SS0_BUS_REF_CLK,
        0
    },
#if 0
    /* Known issue not to work with firmware, Query Call fails */
    /* USB0_REF_CLK_SEL supports 20MHz under specific conditions . See clocking spec */
    {
        TISCI_DEV_USB3SS0,
        TISCI_DEV_USB3SS0_BUS_REF_CLK,
        20000000
    },
#endif
    {
        TISCI_DEV_USB3SS0,
        TISCI_DEV_USB3SS0_BUS_HSIC_CLK_CLK,
        0
    },
    {
        TISCI_DEV_USB3SS0,
        TISCI_DEV_USB3SS0_BUS_BUS_CLK,
        0
    },
    {
        TISCI_DEV_USB3SS0,
        TISCI_DEV_USB3SS0_BUS_PIPE3_TXB_CLK,
        0
    },
    {
        TISCI_DEV_USB3SS0,
        TISCI_DEV_USB3SS0_BUS_UTMI_CLK_CLK,
        0
    },
    {
        TISCI_DEV_USB3SS1,
        TISCI_DEV_USB3SS1_BUS_SUSP_CLK,
        0
    },
    {
        TISCI_DEV_USB3SS1,
        TISCI_DEV_USB3SS1_BUS_PHY2_REFCLK960M_CLK,
        0
    },
    /* Default for USB1_REF_CLK_SEl is from MAIN_PLL_REF_CLK */
    {
        TISCI_DEV_USB3SS1,
        TISCI_DEV_USB3SS1_BUS_REF_CLK,
        0
    },
    {
        TISCI_DEV_USB3SS1,
        TISCI_DEV_USB3SS1_BUS_HSIC_CLK_CLK,
        0
    },
    {
        TISCI_DEV_USB3SS1,
        TISCI_DEV_USB3SS1_BUS_BUS_CLK,
        0
    },
    {
        TISCI_DEV_USB3SS1,
        TISCI_DEV_USB3SS1_BUS_PIPE3_TXB_CLK,
        0
    },
    {
        TISCI_DEV_USB3SS1,
        TISCI_DEV_USB3SS1_BUS_UTMI_CLK_CLK,
        0
    },
    {
        TISCI_DEV_SERDES0,
        TISCI_DEV_SERDES0_BUS_IP3_LN0_TXRCLK,
        0
    },
    {
        TISCI_DEV_SERDES0,
        TISCI_DEV_SERDES0_BUS_REFCLKPP,
        0
    },
    {
        TISCI_DEV_SERDES0,
        TISCI_DEV_SERDES0_BUS_CLK,
        0
    },
    {
        TISCI_DEV_SERDES0,
        TISCI_DEV_SERDES0_BUS_IP2_LN0_TXRCLK,
        0
    },
    {
        TISCI_DEV_SERDES0,
        TISCI_DEV_SERDES0_BUS_LI_REFCLK,
        25000000
    },
    {
        TISCI_DEV_SERDES0,
        TISCI_DEV_SERDES0_BUS_LI_REFCLK,
        100000000
    },
    {
        TISCI_DEV_SERDES0,
        TISCI_DEV_SERDES0_BUS_LI_REFCLK,
        125000000
    },
    {
        TISCI_DEV_SERDES0,
        TISCI_DEV_SERDES0_BUS_REFCLKPN,
        0
    },
    {
        TISCI_DEV_SERDES0,
        TISCI_DEV_SERDES0_BUS_LN0_TXCLK,
        0
    },
    {
        TISCI_DEV_SERDES0,
        TISCI_DEV_SERDES0_BUS_LN0_RXCLK,
        0
    },
    {
        TISCI_DEV_SERDES1,
        TISCI_DEV_SERDES1_BUS_IP3_LN0_TXRCLK,
        0
    },
    {
        TISCI_DEV_SERDES1,
        TISCI_DEV_SERDES1_BUS_REFCLKPP,
        0
    },
    {
        TISCI_DEV_SERDES1,
        TISCI_DEV_SERDES1_BUS_CLK,
        0
    },
    {
        TISCI_DEV_SERDES1,
        TISCI_DEV_SERDES1_BUS_IP1_LN0_TXRCLK,
        0
    },
    {
        TISCI_DEV_SERDES1,
        TISCI_DEV_SERDES1_BUS_IP2_LN0_TXRCLK,
        0
    },
    {
        TISCI_DEV_SERDES1,
        TISCI_DEV_SERDES1_BUS_RI_REFCLK,
        100000000
    },
    {
        TISCI_DEV_SERDES1,
        TISCI_DEV_SERDES1_BUS_RI_REFCLK,
        125000000
    },
    {
        TISCI_DEV_SERDES1,
        TISCI_DEV_SERDES1_BUS_REFCLKPN,
        0
    },
    {
        TISCI_DEV_SERDES1,
        TISCI_DEV_SERDES1_BUS_LN0_TXCLK,
        0
    },
    {
        TISCI_DEV_SERDES1,
        TISCI_DEV_SERDES1_BUS_LN0_RXCLK,
        0
    },
    {
        TISCI_DEV_WKUP_CTRL_MMR0,
        TISCI_DEV_WKUP_CTRL_MMR0_BUS_VBUSP_CLK,
        0
    },
    {
        TISCI_DEV_WKUP_GPIOMUX_INTRTR0,
        TISCI_DEV_WKUP_GPIOMUX_INTRTR0_BUS_INTR_CLK,
        0
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_MSMC0,
        TISCI_DEV_COMPUTE_CLUSTER_MSMC0_BUS_TB_SOC_VBUSP_DMSC_CLK,
        0
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_MSMC0,
        TISCI_DEV_COMPUTE_CLUSTER_MSMC0_BUS_TB_SOC_VBUSP_DBG_CLK,
        0
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_MSMC0,
        TISCI_DEV_COMPUTE_CLUSTER_MSMC0_BUS_MSMC_CLK,
        0
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_MSMC0,
        TISCI_DEV_COMPUTE_CLUSTER_MSMC0_BUS_TB_SOC_VBUSP_CFG_CLK,
        0
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_MSMC0,
        TISCI_DEV_COMPUTE_CLUSTER_MSMC0_BUS_TB_SOC_GIC_CLK,
        0
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_CPAC0,
        TISCI_DEV_COMPUTE_CLUSTER_CPAC0_BUS_ARM0_CLK,
        0
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_CPAC1,
        TISCI_DEV_COMPUTE_CLUSTER_CPAC1_BUS_ARM1_CLK,
        0
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_0,
        TISCI_DEV_COMPUTE_CLUSTER_A53_0_BUS_ARM0_CLK,
        400000000
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_0,
        TISCI_DEV_COMPUTE_CLUSTER_A53_0_BUS_ARM0_CLK,
        800000000
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_0,
        TISCI_DEV_COMPUTE_CLUSTER_A53_0_BUS_ARM0_CLK,
        1000000000
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_0,
        TISCI_DEV_COMPUTE_CLUSTER_A53_0_BUS_ARM0_CLK,
        1100000000
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_1,
        TISCI_DEV_COMPUTE_CLUSTER_A53_1_BUS_ARM0_CLK,
        400000000
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_1,
        TISCI_DEV_COMPUTE_CLUSTER_A53_1_BUS_ARM0_CLK,
        800000000
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_1,
        TISCI_DEV_COMPUTE_CLUSTER_A53_1_BUS_ARM0_CLK,
        1000000000
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_1,
        TISCI_DEV_COMPUTE_CLUSTER_A53_1_BUS_ARM0_CLK,
        1100000000
    },
#if 0 
    /* Not Working in 2019.01a. The system firmware would crash in this configuration. */
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_2,
        TISCI_DEV_COMPUTE_CLUSTER_A53_2_BUS_ARM1_CLK,
        400000000
    },
#endif

    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_2,
        TISCI_DEV_COMPUTE_CLUSTER_A53_2_BUS_ARM1_CLK,
        800000000
    },
#if 0 
    /* Not Working in 2019.01a. The system firmware would crash in this configuration. */
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_2,
        TISCI_DEV_COMPUTE_CLUSTER_A53_2_BUS_ARM1_CLK,
        1000000000
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_2,
        TISCI_DEV_COMPUTE_CLUSTER_A53_2_BUS_ARM1_CLK,
        1100000000
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_3,
        TISCI_DEV_COMPUTE_CLUSTER_A53_3_BUS_ARM1_CLK,
        400000000
    },
#endif
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_3,
        TISCI_DEV_COMPUTE_CLUSTER_A53_3_BUS_ARM1_CLK,
        800000000
    },
#if 0
    /* Not Working in 2019.01a. The system firmware would crash in this configuration. */
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_3,
        TISCI_DEV_COMPUTE_CLUSTER_A53_3_BUS_ARM1_CLK,
        1000000000
    },
    {
        TISCI_DEV_COMPUTE_CLUSTER_A53_3,
        TISCI_DEV_COMPUTE_CLUSTER_A53_3_BUS_ARM1_CLK,
        1100000000
    },
#endif
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVSRAMLO_4,
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVSRAMLO_4_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVSRAMLO_4,
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVSRAMLO_4_BUS_PROBE_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_FSS_S1_3,
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_FSS_S1_3_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_FSS_S1_3,
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_FSS_S1_3_BUS_PROBE_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_EXPORT_SLV_0,
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_EXPORT_SLV_0_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_EXPORT_SLV_0,
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_EXPORT_SLV_0_BUS_PROBE_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVSRAMHI_3,
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVSRAMHI_3_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVSRAMHI_3,
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVSRAMHI_3_BUS_PROBE_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_SRAM_SLV_1,
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_SRAM_SLV_1_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_SRAM_SLV_1,
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_SRAM_SLV_1_BUS_PROBE_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVDDRHI_5,
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVDDRHI_5_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVDDRHI_5,
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVDDRHI_5_BUS_PROBE_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVDDRLO_6,
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVDDRLO_6_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVDDRLO_6,
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_NAVDDRLO_6_BUS_PROBE_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_CAL0_0,
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_CAL0_0_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_CAL0_0,
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_CAL0_0_BUS_PROBE_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_DSS_2,
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_DSS_2_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_DSS_2,
        TISCI_DEV_CPT2_PROBE_VBUSM_MAIN_DSS_2_BUS_PROBE_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_FSS_S0_2,
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_FSS_S0_2_BUS_VBUS_CLK,
        0
    },
    {
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_FSS_S0_2,
        TISCI_DEV_CPT2_PROBE_VBUSM_MCU_FSS_S0_2_BUS_PROBE_CLK,
        0
    },
    {
        TISCI_DEV_OLDI_TX_CORE_MAIN_0,
        TISCI_DEV_OLDI_TX_CORE_MAIN_0_BUS_OLDI_PLL_CLK,
        0
    },
    {
        TISCI_DEV_OLDI_TX_CORE_MAIN_0,
        TISCI_DEV_OLDI_TX_CORE_MAIN_0_BUS_OLDI_0_FWD_P_CLK_BUS_IN1_CLOCKDIVIDER_DSS_BUS_OUT0,
        0
    },
    {
        TISCI_DEV_OLDI_TX_CORE_MAIN_0,
        TISCI_DEV_OLDI_TX_CORE_MAIN_0_BUS_OLDI_0_FWD_P_CLK_BUS_IN0_CLOCKDIVIDER_DSS_BUS_OUT0,
        0
    },
    {
        TISCI_DEV_K3_ARM_ATB_FUNNEL_3_32_MCU_0,
        TISCI_DEV_K3_ARM_ATB_FUNNEL_3_32_MCU_0_BUS_DBG_CLK,
        0
    },
    {
        TISCI_DEV_GS80PRG_SOC_WRAP_WKUP_0,
        TISCI_DEV_GS80PRG_SOC_WRAP_WKUP_0_BUS_OSC_CLK,
        0
    },
    {
        TISCI_DEV_GS80PRG_SOC_WRAP_WKUP_0,
        TISCI_DEV_GS80PRG_SOC_WRAP_WKUP_0_BUS_CLK,
        0
    },
    {
        TISCI_DEV_GS80PRG_MCU_WRAP_WKUP_0,
        TISCI_DEV_GS80PRG_MCU_WRAP_WKUP_0_BUS_OSC_CLK,
        0
    },
    {
        TISCI_DEV_GS80PRG_MCU_WRAP_WKUP_0,
        TISCI_DEV_GS80PRG_MCU_WRAP_WKUP_0_BUS_CLK,
        0
    },
    {
        TISCI_DEV_MX_EFUSE_MAIN_CHAIN_MAIN_0,
        TISCI_DEV_MX_EFUSE_MAIN_CHAIN_MAIN_0_BUS_UNDEFINEDCHAIN1_FCLK,
        0
    },
    {
        TISCI_DEV_MX_EFUSE_MAIN_CHAIN_MAIN_0,
        TISCI_DEV_MX_EFUSE_MAIN_CHAIN_MAIN_0_BUS_UNDEFINEDCHAIN0_FCLK,
        0
    },
    {
        TISCI_DEV_MX_EFUSE_MCU_CHAIN_MCU_0,
        TISCI_DEV_MX_EFUSE_MCU_CHAIN_MCU_0_BUS_UNDEFINEDCHAIN1_FCLK,
        0
    },
    {
        TISCI_DEV_MX_EFUSE_MCU_CHAIN_MCU_0,
        TISCI_DEV_MX_EFUSE_MCU_CHAIN_MCU_0_BUS_UNDEFINEDCHAIN0_FCLK,
        0
    },
    {
        TISCI_DEV_MX_EFUSE_MCU_CHAIN_MCU_0,
        TISCI_DEV_MX_EFUSE_MCU_CHAIN_MCU_0_BUS_UNDEFINEDCHAIN2_FCLK,
        0
    },
};
#ifdef __cplusplus
}
#endif
#endif /* PMTEST_TESTSLIST_AM65XX_H_ */

